version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nestif
    - nilerr
    - noctx
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    goconst:
      min-len: 20
      min-occurrences: 5
      ignore-calls: false
    gocritic:
      disabled-checks:
        - unnamedResult
        - hugeParam
        - singleCaseSwitch
        - ifElseChain
        - nestingReduce
        - dupOption
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
        - name: useless-break
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - deadcode
          - unused
        path: _test\.go
      - linters:
          - staticcheck
        text: error strings should not be capitalized
      - linters:
          - staticcheck
        path: _test\.go
        text: should not use underscores in Go names
      - linters:
          - gocritic
        text: paramTypeCombine
      - linters:
          - errcheck
        path: \.go
      - linters:
          - gocritic
        path: resource_tfe_policy_set\.go
        text: badRegexp
      - linters:
          - gocritic
        path: data_source_ip_ranges_test\.go
        text: 'regexpSimplify: can re-write'
      - linters:
          - gosec
        path: (_test|workspace_run_helpers)\.go
      - linters:
          - nestif
        path: (resource_tfe_team_access|resource_tfe_workspace|credentials|resource_tfe_policy_set| resource_tfe_policy_set|resource_tfe_team_members|resource_tfe_notification_configuration|resource_tfe_team)\.go
      - linters:
          - unparam
        path: _test\.go
        text: always receives
      - linters:
          - errorlint
        path: (data_source_organization|data_source_variable_set|data_source_workspace|resource_tfe_organization_token| -|resource_tfe_team_token|plugin_provider_test|resource_tfe_agent_pool|resource_tfe_agent_token|resource_tfe_organization_module_sharing| -|resource_tfe_policy_set|resource_tfe_policy_set_parameter|resource_tfe_team_members_test|resource_tfe_team_organization_member_test| -|resource_tfe_notification_configuration|resource_tfe_oauth_client|resource_tfe_organization|resource_tfe_organization_membership|resource_tfe_team_members| -|resource_tfe_registry_module|resource_tfe_run_trigger|resource_tfe_sentinel_policy|resource_tfe_ssh_key|resource_tfe_team|resource_tfe_team_access| -|resource_tfe_team_member|resource_tfe_team_organization_member|resource_tfe_terraform_version|resource_tfe_variable_set|resource_tfe_variable| -|resource_tfe_workspace|workspace_helpers)\.go
        text: comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
      - linters:
          - errorlint
        path: provider\.go
        text: type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors
      - linters:
          - staticcheck
        path: resource_tfe_workspace\.go
        text: 'S1002: should omit comparison to bool constant'
      - linters:
          - staticcheck
        path: data_source_ip_ranges_test\.go
        text: 'S1039: unnecessary use of fmt.Sprintf'
      - linters:
          - staticcheck
        path: resource_tfe_team_members_test\.go
        text: 'S1019: should use make'
      - linters:
          - staticcheck
        path: (resource_tfe_team_access_migrate_test|workspace_helpers_test)\.go
        text: 'SA1012: do not pass a nil Context, even if a function permits it; pass context.TODO if you are unsure about which Context to use'
      - linters:
          - staticcheck
        path: (data_source_outputs|resource_tfe_agent_pool|resource_tfe_notification_configuration|resource_tfe_organization|resource_tfe_registry_module| -|resource_tfe_run_trigger|resource_tfe_team_access|resource_tfe_organization_membership|resource_tfe_policy_set|resource_tfe_team_member| -|resource_tfe_workspace|resource_tfe_team_organization_member|resource_tfe_variable_set|resource_tfe_team_project_access)\.go
        text: SA1019
      - linters:
          - staticcheck
        path: resource_tfe_workspace_run_task\.go
        text: 'SA1019: v.Stage is deprecated: Use Stages property instead'
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
