# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Lint
description: Lints terraform-provider-tfe
runs:
  using: composite
  steps:
    - name: Setup Go Environment
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: "go.mod"
        cache: true

    - name: fmt check
      run: make fmtcheck
      shell: bash

    - name: go vet
      run: make vet
      shell: bash

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/0b5709648c8ba9780e821faf16c5c2bb3262ce3e/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCILINT_VERSION
      shell: bash
      env:
        GOLANGCILINT_VERSION: v1.55.2

    - run: make lint
      shell: bash
