# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Lint
description: Lints terraform-provider-tfe
runs:
  using: composite
  steps:
    - name: Setup Go Environment
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
      with:
        go-version-file: "go.mod"
        cache: true
        cache-dependency-path: go.sum

    - name: fmt check
      run: make fmtcheck
      shell: bash

    - name: go vet
      run: make vet
      shell: bash

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/fca8610ee8fe3bf0bc2e8b7be7c674dd26aaa289/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCILINT_VERSION
      shell: bash
      env:
        GOLANGCILINT_VERSION: v1.64.8

    - name: Run golangci-lint
      run: make lint
      shell: bash
