#!/usr/bin/env bash
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0


set +x
set -e

OVERRIDE_CLI_CONFIG=provider_tfe_override.tfrc

if [ ! -f "$OVERRIDE_CLI_CONFIG" ]; then
  tee -a $OVERRIDE_CLI_CONFIG > /dev/null <<EOT
# This file was generated by ./scripts/devoverride.sh
provider_installation {
  dev_overrides {
    "hashicorp/tfe" = "$(pwd)"
  }

  direct {}
}
EOT
fi

echo "export TF_CLI_CONFIG_FILE=$(pwd)/$OVERRIDE_CLI_CONFIG"
