name: Jira Issue Sync

on:
  issues:
    types: [opened, closed, deleted, reopened]
  issue_comment:
    types: [created]

jobs:
  call-workflow:
    uses: ./.github/workflows/jira-issue-sync.yml
    with:
      project: TF
      issue-extra-fields: |
        { "customfield_10091": ["TF-Core-Cloud"],
          "customfield_10008": "${{ contains(github.event.issue.labels.*.name, 'bug') && 'TF-7331' || 'TF-3484' }}"
        }
    secrets: inherit
